POST  http://localhost:3002/register
Content-Type: application/json

{
    "username":"sweety",
    "email": "sweety@gmail.com",
    "password": "sweety"
}
  
###
POST  http://localhost:3002/login
Content-Type: application/json

{
    "username":"sweety",
    "password": "sweety"
}

###
GET http://localhost:3002/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoiUmFqcGFsIiwiaWF0IjoxNzExNjA5MjU1fQ.EmNN7fFONoSov0vAwBaRLx-LidWvtP27HoTsuA6pY2U


###
GET http://localhost:3002/api/data?category=Animals&limit=5&https=true

###

GET http://localhost:3002/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoiUmFqcGFsIiwiaWF0IjoxNzExNjA5MjU1fQ.EmNN7fFONoSov0vAwBaRLx-LidWvtP27HoTsuA6pY2U



###
PUT http://localhost:3002/changePassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoia2FyIiwiaWF0IjoxNzExNjA4ODAxfQ.-W4nfvjWsnPgLSVXJR0Rm_na8Dx0KqSLN8SYGtjjDQY
Content-Type: application/json

{
    "newPassword": "kar12345"
}



